# Generated by Django 2.2.11 on 2020-03-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('titre', models.CharField(max_length=100)),
                ('evenement', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to=None)),
            ],
        ),
    ]
